name: Snowplow-Scala-Collector
description: |
  Scala Collector for Snowplow
version: 0.0.8
category: Snowplow
maintainer: https://github.com/joshuacox
license: GPL v3
projectURL: https://github.com/WebHostingCoopTeam/whc-catalog
