version: '2'

services:
  gitlab-data:
    labels:
      io.rancher.container.start_once: 'true'
    entrypoint:
    - /bin/true
    hostname: gitdata
    image: gitlab/gitlab-ce:latest
    volume_driver: ${VOLUME_DRIVER}
    volumes:
    - ${VOLUME_NAME}:/home/git/data:Z
    - ${DB_VOLUME_NAME}:/var/lib/postgresql:Z
    - ${REDIS_VOLUME_NAME}:/var/lib/redis:Z
  redis:
    restart: always
    image: sameersbn/redis:latest
    command:
    - --loglevel warning
    volumes_from:
    - gitlab-data

  postgresql:
    restart: always
    image: sameersbn/postgresql:9.6-1
    volumes_from:
    - gitlab-data
    environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
    - DB_EXTENSION=pg_trgm

  gitlab:
    restart: always
    image: sameersbn/gitlab:8.15.4
    depends_on:
    - redis
    - postgresql
    ports:
    - "10080:80"
    - "10022:22"
    volumes_from:
    - gitlab-data
    labels:
      io.rancher.sidekicks: gitlab-data,redis,postgresql
      traefik.enable: true
      traefik.domain: ${gitlab_hostname}
      traefik.port: ${http_port}
    hostname: ${gitlab_hostname}
    environment:
    - DEBUG=${DEBUG}

    - DB_ADAPTER=${DB_ADAPTER}
    - DB_HOST=${DB_HOST}
    - DB_PORT=${DB_PORT}
    - DB_USER=${DB_USER}
    - DB_PASS=${DB_PASS}
    - DB_NAME=${DB_NAME}

    - REDIS_HOST=${REDIS_HOST}
    - REDIS_PORT=${REDIS_PORT}

    - TZ=${TZ}
    - GITLAB_TIMEZONE=${GITLAB_TIMEZONE}

    - GITLAB_HTTPS=${GITLAB_HTTPS}
    - SSL_SELF_SIGNED=${SSL_SELF_SIGNED}

    - GITLAB_HOST=${GITLAB_HOST}
    - GITLAB_PORT=${http_port}
    - GITLAB_SSH_PORT=${ssh_port}
    - GITLAB_RELATIVE_URL_ROOT=${GITLAB_RELATIVE_URL_ROOT}
    - GITLAB_SECRETS_DB_KEY_BASE=${GITLAB_SECRETS_DB_KEY_BASE}
    - GITLAB_SECRETS_SECRET_KEY_BASE=${GITLAB_SECRETS_SECRET_KEY_BASE}
    - GITLAB_SECRETS_OTP_KEY_BASE=${GITLAB_SECRETS_OTP_KEY_BASE}

    - GITLAB_ROOT_PASSWORD=${GITLAB_ROOT_PASSWORD}
    - GITLAB_ROOT_EMAIL=${GITLAB_ROOT_EMAIL}

    - GITLAB_NOTIFY_ON_BROKEN_BUILDS=${GITLAB_NOTIFY_ON_BROKEN_BUILDS}
    - GITLAB_NOTIFY_PUSHER=${GITLAB_NOTIFY_PUSHER}

    - GITLAB_EMAIL=${GITLAB_EMAIL}
    - GITLAB_EMAIL_REPLY_TO=${GITLAB_EMAIL_REPLY_TO}
    - GITLAB_INCOMING_EMAIL_ADDRESS=${GITLAB_INCOMING_EMAIL_ADDRESS}

    - GITLAB_BACKUP_SCHEDULE=${GITLAB_BACKUP_SCHEDULE}
    - GITLAB_BACKUP_TIME=${GITLAB_BACKUP_TIME}

    - SMTP_ENABLED=${SMTP_ENABLED}
    - SMTP_DOMAIN=${SMTP_DOMAIN}
    - SMTP_HOST=${SMTP_HOST}
    - SMTP_PORT=${SMTP_PORT}
    - SMTP_USER=${SMTP_USER}
    - SMTP_PASS=${SMTP_PASS}
    - SMTP_STARTTLS=${SMTP_STARTTLS}
    - SMTP_AUTHENTICATION=${SMTP_AUTHENTICATION}

    - IMAP_ENABLED=${IMAP_ENABLED}
    - IMAP_HOST=${IMAP_HOST}
    - IMAP_PORT=${IMAP_PORT}
    - IMAP_USER=${IMAP_USER}
    - IMAP_PASS=${IMAP_PASS}
    - IMAP_SSL=${IMAP_SSL}
    - IMAP_STARTTLS=${IMAP_STARTTLS}

    - OAUTH_ENABLED=${OAUTH_ENABLED}
    - OAUTH_AUTO_SIGN_IN_WITH_PROVIDER=${OAUTH_AUTO_SIGN_IN_WITH_PROVIDER}
    - OAUTH_ALLOW_SSO=${OAUTH_ALLOW_SSO}
    - OAUTH_BLOCK_AUTO_CREATED_USERS=${OAUTH_BLOCK_AUTO_CREATED_USERS}
    - OAUTH_AUTO_LINK_LDAP_USER=${OAUTH_AUTO_LINK_LDAP_USER}
    - OAUTH_AUTO_LINK_SAML_USER=${OAUTH_AUTO_LINK_SAML_USER}
    - OAUTH_EXTERNAL_PROVIDERS=${OAUTH_EXTERNAL_PROVIDERS}

    - OAUTH_CAS3_LABEL=${OAUTH_CAS3_LABEL}
    - OAUTH_CAS3_SERVER=${OAUTH_CAS3_SERVER}
    - OAUTH_CAS3_DISABLE_SSL_VERIFICATION=${OAUTH_CAS3_DISABLE_SSL_VERIFICATION}
    - OAUTH_CAS3_LOGIN_URL=${OAUTH_CAS3_LOGIN_URL}
    - OAUTH_CAS3_VALIDATE_URL=${OAUTH_CAS3_VALIDATE_URL}
    - OAUTH_CAS3_LOGOUT_URL=${OAUTH_CAS3_LOGOUT_URL}

    - OAUTH_GOOGLE_API_KEY=${OAUTH_GOOGLE_API_KEY}
    - OAUTH_GOOGLE_APP_SECRET=${OAUTH_GOOGLE_APP_SECRET}
    - OAUTH_GOOGLE_RESTRICT_DOMAIN=${OAUTH_GOOGLE_RESTRICT_DOMAIN}

    - OAUTH_FACEBOOK_API_KEY=${OAUTH_FACEBOOK_API_KEY}
    - OAUTH_FACEBOOK_APP_SECRET=${OAUTH_FACEBOOK_APP_SECRET}

    - OAUTH_TWITTER_API_KEY=${OAUTH_TWITTER_API_KEY}
    - OAUTH_TWITTER_APP_SECRET=${OAUTH_TWITTER_APP_SECRET}

    - OAUTH_GITHUB_API_KEY=${OAUTH_GITHUB_API_KEY}
    - OAUTH_GITHUB_APP_SECRET=${OAUTH_GITHUB_APP_SECRET}
    - OAUTH_GITHUB_URL=${OAUTH_GITHUB_URL}
    - OAUTH_GITHUB_VERIFY_SSL=${OAUTH_GITHUB_VERIFY_SSL}

    - OAUTH_GITLAB_API_KEY=${OAUTH_GITLAB_API_KEY}
    - OAUTH_GITLAB_APP_SECRET=${OAUTH_GITLAB_APP_SECRET}

    - OAUTH_BITBUCKET_API_KEY=${OAUTH_BITBUCKET_API_KEY}
    - OAUTH_BITBUCKET_APP_SECRET=${OAUTH_BITBUCKET_APP_SECRET}

    - OAUTH_SAML_ASSERTION_CONSUMER_SERVICE_URL=${OAUTH_SAML_ASSERTION_CONSUMER_SERVICE_URL}
    - OAUTH_SAML_IDP_CERT_FINGERPRINT=${OAUTH_SAML_IDP_CERT_FINGERPRINT}
    - OAUTH_SAML_IDP_SSO_TARGET_URL=${OAUTH_SAML_IDP_SSO_TARGET_URL}
    - OAUTH_SAML_ISSUER=${OAUTH_SAML_ISSUER}
    - OAUTH_SAML_LABEL=${OAUTH_SAML_LABEL}
    - OAUTH_SAML_NAME_IDENTIFIER_FORMAT=${OAUTH_SAML_NAME_IDENTIFIER_FORMAT}
    - OAUTH_SAML_GROUPS_ATTRIBUTE=${OAUTH_SAML_GROUPS_ATTRIBUTE}
    - OAUTH_SAML_EXTERNAL_GROUPS=${OAUTH_SAML_EXTERNAL_GROUPS}
    - OAUTH_SAML_ATTRIBUTE_STATEMENTS_EMAIL=${OAUTH_SAML_ATTRIBUTE_STATEMENTS_EMAIL}
    - OAUTH_SAML_ATTRIBUTE_STATEMENTS_NAME=${OAUTH_SAML_ATTRIBUTE_STATEMENTS_NAME}
    - OAUTH_SAML_ATTRIBUTE_STATEMENTS_FIRST_NAME=${OAUTH_SAML_ATTRIBUTE_STATEMENTS_FIRST_NAME}
    - OAUTH_SAML_ATTRIBUTE_STATEMENTS_LAST_NAME=${OAUTH_SAML_ATTRIBUTE_STATEMENTS_LAST_NAME}

    - OAUTH_CROWD_SERVER_URL=${OAUTH_CROWD_SERVER_URL}
    - OAUTH_CROWD_APP_NAME=${OAUTH_CROWD_APP_NAME}
    - OAUTH_CROWD_APP_PASSWORD=${OAUTH_CROWD_APP_PASSWORD}

    - OAUTH_AUTH0_CLIENT_ID=${OAUTH_AUTH0_CLIENT_ID}
    - OAUTH_AUTH0_CLIENT_SECRET=${OAUTH_AUTH0_CLIENT_SECRET}
    - OAUTH_AUTH0_DOMAIN=${OAUTH_AUTH0_DOMAIN}

    - OAUTH_AZURE_API_KEY=${OAUTH_AZURE_API_KEY}
    - OAUTH_AZURE_API_SECRET=${OAUTH_AZURE_API_SECRET}
    - OAUTH_AZURE_TENANT_ID=${OAUTH_AZURE_TENANT_ID}
