name: Drupal
description: |
 Launch, manage, and scale ambitious digital experiencesâ€”with the flexibility to build great websites or push beyond the browser. Proudly open source.
version: 0.1.0
category: CMS
